// <auto-generated />
using System;
using DataLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(StackInternshipDbContext))]
    [Migration("20211223120048_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPublishing")
                        .HasColumnType("datetime2");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("int");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CommentId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "ok",
                            DateOfPublishing = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownvoteCount = 0,
                            UpvoteCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Content = "Može",
                            DateOfPublishing = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DownvoteCount = 0,
                            UpvoteCount = 0
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPublishing")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("int");

                    b.Property<int>("RoleOfAuthor")
                        .HasColumnType("int");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "Prva obavijest",
                            DateOfPublishing = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 4,
                            DownvoteCount = 0,
                            RoleOfAuthor = 0,
                            UpvoteCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Content = "Kad je iduće predavanje?",
                            DateOfPublishing = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 0,
                            DownvoteCount = 0,
                            RoleOfAuthor = 0,
                            UpvoteCount = 0
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrustedUser")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Matea",
                            IsTrustedUser = false,
                            LastName = "Baturina",
                            Password = "1234",
                            ReputationPoints = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Lovre",
                            IsTrustedUser = false,
                            LastName = "Cikojević",
                            Password = "4321",
                            ReputationPoints = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Bartol",
                            IsTrustedUser = false,
                            LastName = "Deak",
                            Password = "qwe",
                            ReputationPoints = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Mislav",
                            IsTrustedUser = false,
                            LastName = "Maretić",
                            Password = "ewq",
                            ReputationPoints = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Anamarija",
                            IsTrustedUser = false,
                            LastName = "Papić",
                            Password = "password",
                            ReputationPoints = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Bože",
                            IsTrustedUser = false,
                            LastName = "Topić",
                            Password = "sifra",
                            ReputationPoints = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Petra",
                            IsTrustedUser = false,
                            LastName = "Zelić",
                            Password = "1950",
                            ReputationPoints = 1,
                            Role = 0
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Models.Comment", b =>
                {
                    b.HasOne("DataLayer.Entities.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Models.Comment", null)
                        .WithMany("Subcomments")
                        .HasForeignKey("CommentId");

                    b.HasOne("DataLayer.Entities.Models.Resource", null)
                        .WithMany("Comments")
                        .HasForeignKey("ResourceId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DataLayer.Entities.Models.Resource", b =>
                {
                    b.HasOne("DataLayer.Entities.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DataLayer.Entities.Models.Comment", b =>
                {
                    b.Navigation("Subcomments");
                });

            modelBuilder.Entity("DataLayer.Entities.Models.Resource", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
