// <auto-generated />
using System;
using DataLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(StackInternshipDbContext))]
    [Migration("20220107155741_RestorationAfterDeletion")]
    partial class RestorationAfterDeletion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Entities.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<int>("DownvoteCount")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeOfEntry")
                        .HasColumnType("int");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CommentCount = 1,
                            Content = "Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.",
                            Department = 53,
                            DownvoteCount = 0,
                            ParentId = 0,
                            PublishedAt = new DateTime(2021, 12, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfEntry = 0,
                            UpvoteCount = 0,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            CommentCount = 0,
                            Content = "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.",
                            Department = 49,
                            DownvoteCount = 0,
                            ParentId = 0,
                            PublishedAt = new DateTime(2021, 12, 1, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            TypeOfEntry = 0,
                            UpvoteCount = 0,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CommentCount = 0,
                            Content = "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.",
                            Department = 50,
                            DownvoteCount = 0,
                            ParentId = 0,
                            PublishedAt = new DateTime(2021, 12, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            TypeOfEntry = 0,
                            UpvoteCount = 0,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CommentCount = 0,
                            Content = "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
                            Department = 49,
                            DownvoteCount = 0,
                            ParentId = 0,
                            PublishedAt = new DateTime(2021, 12, 1, 0, 30, 0, 0, DateTimeKind.Unspecified),
                            TypeOfEntry = 0,
                            UpvoteCount = 0,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CommentCount = 0,
                            Content = "Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.",
                            Department = 53,
                            DownvoteCount = 0,
                            ParentId = 0,
                            PublishedAt = new DateTime(2021, 12, 1, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            TypeOfEntry = 0,
                            UpvoteCount = 0,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            CommentCount = 1,
                            Content = "Quisque erat eros, viverra eget.",
                            Department = 53,
                            DownvoteCount = 0,
                            ParentId = 1,
                            PublishedAt = new DateTime(2022, 1, 1, 12, 13, 14, 0, DateTimeKind.Unspecified),
                            TypeOfEntry = 1,
                            UpvoteCount = 0,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            CommentCount = 0,
                            Content = "Maecenas ut massa quis augue luctus tincidunt.",
                            Department = 53,
                            DownvoteCount = 0,
                            ParentId = 6,
                            PublishedAt = new DateTime(2022, 1, 3, 12, 13, 14, 0, DateTimeKind.Unspecified),
                            TypeOfEntry = 2,
                            UpvoteCount = 0,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeactivatedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTrustedUser")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PermanentDeactivation")
                        .HasColumnType("bit");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsTrustedUser = false,
                            Password = "12345",
                            PermanentDeactivation = false,
                            ReputationPoints = 10,
                            Role = 0,
                            UserName = "MateaB"
                        },
                        new
                        {
                            Id = 2,
                            IsTrustedUser = true,
                            Password = "54321",
                            PermanentDeactivation = false,
                            ReputationPoints = 444444,
                            Role = 1,
                            UserName = "lovre"
                        },
                        new
                        {
                            Id = 3,
                            IsTrustedUser = false,
                            Password = "qweqw",
                            PermanentDeactivation = false,
                            ReputationPoints = 1,
                            Role = 0,
                            UserName = "bartol_deak"
                        },
                        new
                        {
                            Id = 4,
                            IsTrustedUser = false,
                            Password = "qwqwq",
                            PermanentDeactivation = false,
                            ReputationPoints = 990,
                            Role = 0,
                            UserName = "mmaretic"
                        },
                        new
                        {
                            Id = 5,
                            IsTrustedUser = false,
                            Password = "password",
                            PermanentDeactivation = false,
                            ReputationPoints = 1,
                            Role = 0,
                            UserName = "Anamarija"
                        },
                        new
                        {
                            Id = 6,
                            IsTrustedUser = false,
                            Password = "sifra",
                            PermanentDeactivation = false,
                            ReputationPoints = 1,
                            Role = 0,
                            UserName = "Boze Topic"
                        },
                        new
                        {
                            Id = 7,
                            IsTrustedUser = true,
                            Password = "asdas",
                            PermanentDeactivation = false,
                            ReputationPoints = 200000,
                            Role = 1,
                            UserName = "petra123"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Models.UserEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Viewed")
                        .HasColumnType("bit");

                    b.Property<bool>("Voted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.Models.Entry", b =>
                {
                    b.HasOne("DataLayer.Entities.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DataLayer.Entities.Models.UserEntry", b =>
                {
                    b.HasOne("DataLayer.Entities.Models.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataLayer.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
